name: Deploy Workspace Environment and Files

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      ABSTRA_API_TOKEN: ${{ secrets.ABSTRA_API_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup
        run: pip install --upgrade abstra

      - name: Deploy
        run: abstra deploy 